### PR TITLE
release: v0.0.1 first release version of OCR app

### PR DESCRIPTION
**Pull request by Huy1711**
Features delivered:

- Support input file formats: .png, .heic, .tiff, .pdf, .doc, .docx
- Support feature OCR using tesseract
- Support feature save output (original images + json location result) to local folder
- Support feature upload to Google Drive
- Unit test + Integration test
- Set up CI (github action) for auto run pre-commit + auto run test cases
- Documentation: App design (UML class diagram), README file

### CODE REVIEW

**Comment by hoang1645** [comment]
image
image

**Comment by hoang1645** [comment]
@haminhle192 should this be cited that they weren't following trunk-based flow?

**Review by hoang1645 — CHANGES_REQUESTED** [review]
- Docstrings found only for some classes, and none for their methods. Maybe I am being pedantic but I would like to request docstrings for all classes and if possible, their methods as well
- Also please add the version annotations for `requirements.txt`.

**Review by Qcymaq — CHANGES_REQUESTED** [review]
It appears that despite following the steps outlined in the README file, I'm encountering the FileNotFoundError: 'secrets\\client_secrets.json' issue. I have already applied the Google Drive API key as instructed.
Please check if team have double-check the file path configuration to ensure it points to the correct location.

**Review by khankaholic — CHANGES_REQUESTED** [review]
It seems a bit bloated to keep such an exhausting commit history. Please consider squashing them into several main commits if possible.

**Review by hungpham3112 — APPROVED** [review]

**Comment by thaohp113** [comment]
> * Docstrings found only for some classes, and none for their methods. Maybe I am being pedantic but I would like to request docstrings for all classes and if possible, their methods as well
> * Also please add the version annotations for `requirements.txt`.

Thank you for the comment! We have updated docstrings for the class and method, and the requirement versions as well.

**Comment by micache** [comment]
> It appears that despite following the steps outlined in the README file, I'm encountering the FileNotFoundError: 'secrets\client_secrets.json' issue. I have already applied the Google Drive API key as instructed. Please check if team have double-check the file path configuration to ensure it points to the correct location.

We fixed this issue. Please follow the README.md and test again.

**Review by hoang1645 — APPROVED** [review]

**Review by NamSee04 — APPROVED** [review]

**Review by Qcymaq — APPROVED** [review]

**Review by khankaholic — APPROVED** [review]

**Pull request merged**
